use PGTrainingDS
Go

CREATE TABLE CUSTOMERS5( 
   ID   INT              NOT NULL, 
   NAME VARCHAR (20)     NOT NULL, 
   AGE  INT              NOT NULL, 
   ADDRESS  CHAR (25) , 
   SALARY   DECIMAL (18, 2),        
   PRIMARY KEY (ID));

   select * from CUSTOMERS5;

INSERT INTO CUSTOMERS5(ID, NAME, AGE, ADDRESS, SALARY) 
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS5(ID,NAME,AGE,ADDRESS,SALARY) 
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS5(ID,NAME,AGE,ADDRESS,SALARY) 
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );  

INSERT INTO CUSTOMERS5(ID,NAME,AGE,ADDRESS,SALARY) 
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

INSERT INTO CUSTOMERS5 VALUES
(8, 'Vijay', 24, 'Indore', 10000.00 );


UPDATE TABLE
UPDATE CUSTOMERS5
SET ADDRESS = 'HyD', AGE=30, SALARY=5000 
WHERE ID = 6;   

select * from CUSTOMERS5;

DELETE FROM CUSTOMERS5 
WHERE ID = 6;

SELECT ID, NAME, SALARY  
FROM CUSTOMERS5 
WHERE SALARY = 8500;

SELECT ID, NAME, SALARY  
FROM CUSTOMERS5
WHERE NAME = 'Hardik';
-- Strings where last name starts with A, B, or C
SELECT * FROM CUSTOMERS5 
WHERE ADDRESS NOT LIKE 'M%'; 

